sudo: false  # Use the new infrastructure

language: php

php:
    - 5.3
    - 5.4

before_install: npm install -g grunt-cli
install: npm install
cache:
    directories:
        - node_modules
        - vendor
script: grunt test
